name: Build & Release
on:
  push:
    tags:
      - "v*"

env:
  GO_VERSION: "1.23.x"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: go build ./cmd/dmverity-vhd
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
      - run: go build ./cmd/dmverity-vhd
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0
      - run: go build -o dmverity-vhd-darwin-amd64 ./cmd/dmverity-vhd
        env:
          GOOS: darwin
          GOARCH: amd64
          CGO_ENABLED: 0
      - run: go build -o dmverity-vhd-darwin-arm64 ./cmd/dmverity-vhd
        env:
          GOOS: darwin
          GOARCH: arm64
          CGO_ENABLED: 0

      - run: cp CimWriter/LICENSE.pdf CimWriter.LICENSE.pdf

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: binaries
          path: |
            dmverity-vhd.exe
            dmverity-vhd
            dmverity-vhd-darwin-amd64
            dmverity-vhd-darwin-arm64
            CimWriter/CimWriter.dll
            CimWriter.LICENSE.pdf

  draft_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: binaries

      - name: Publish draft release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          # This is to make sure that the release is not created if a non-rc tag is pushed
          draft: true
          generate_release_notes: true
          files: |
            dmverity-vhd.exe
            dmverity-vhd
            dmverity-vhd-darwin-amd64
            dmverity-vhd-darwin-arm64
            CimWriter/CimWriter.dll
            CimWriter.LICENSE.pdf
